'use client'

import { useState } from 'react'
import { ImageVariation } from '@/app/campaigns/page'

interface ImageVariationPickerProps {
    platform: string
    variations: ImageVariation[]
    selectedIndex: number
    onSelect: (index: number) => void
    onClose: () => void
}

export function ImageVariationPicker({ platform, variations, selectedIndex, onSelect, onClose }: ImageVariationPickerProps) {
    const [hoveredIndex, setHoveredIndex] = useState<number | null>(null)
    const [zoomedImage, setZoomedImage] = useState<string | null>(null)

    const getModelColor = (modelId: string) => {
        switch (modelId) {
            case 'flux-pro': return 'from-purple-500/20 to-violet-500/20 border-purple-500/50'
            case 'flux-schnell': return 'from-blue-500/20 to-cyan-500/20 border-blue-500/50'
            case 'stable-diffusion-xl': return 'from-orange-500/20 to-amber-500/20 border-orange-500/50'
            default: return 'from-gray-500/20 to-gray-600/20 border-gray-500/50'
        }
    }

    const getModelBadgeColor = (modelId: string) => {
        switch (modelId) {
            case 'flux-pro': return 'bg-purple-500/20 text-purple-400'
            case 'flux-schnell': return 'bg-blue-500/20 text-blue-400'
            case 'stable-diffusion-xl': return 'bg-orange-500/20 text-orange-400'
            default: return 'bg-gray-500/20 text-gray-400'
        }
    }

    const isFailed = (url: string) => url.includes('placehold.co')

    return (
        <>
            <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-6">
                <div className="bg-gray-900 rounded-2xl border border-gray-700/50 w-full max-w-6xl max-h-[90vh] overflow-hidden flex flex-col">
                    {/* Header */}
                    <div className="p-6 border-b border-gray-700/50 flex items-center justify-between">
                        <div>
                            <h2 className="text-xl font-bold text-white flex items-center gap-2">
                                🖼️ Compare Image Variations
                            </h2>
                            <p className="text-gray-400 text-sm mt-1">
                                {variations.length} images generated by different AI models for <span className="text-violet-400 font-medium">{platform}</span>
                            </p>
                        </div>
                        <button
                            onClick={onClose}
                            className="w-10 h-10 rounded-lg bg-gray-800 text-gray-400 hover:text-white hover:bg-gray-700 transition-colors flex items-center justify-center"
                        >
                            ✕
                        </button>
                    </div>

                    {/* Images Grid */}
                    <div className="flex-1 overflow-auto p-6">
                        <div className={`grid gap-6 ${variations.length === 2 ? 'grid-cols-2' : 'grid-cols-3'}`}>
                            {variations.map((variation, index) => {
                                const isSelected = selectedIndex === index
                                const isHovered = hoveredIndex === index
                                const failed = isFailed(variation.imageUrl)

                                return (
                                    <div
                                        key={index}
                                        onClick={() => !failed && onSelect(index)}
                                        onMouseEnter={() => setHoveredIndex(index)}
                                        onMouseLeave={() => setHoveredIndex(null)}
                                        className={`
                                            relative rounded-xl border-2 transition-all cursor-pointer overflow-hidden
                                            ${failed
                                                ? 'opacity-50 cursor-not-allowed border-gray-700/50'
                                                : isSelected
                                                    ? `bg-gradient-to-br ${getModelColor(variation.modelId)} shadow-lg shadow-violet-500/20`
                                                    : isHovered
                                                        ? 'border-gray-600 shadow-lg'
                                                        : 'border-gray-700/50'
                                            }
                                        `}
                                    >
                                        {/* Model Badge */}
                                        <div className="absolute top-3 left-3 z-10 flex items-center gap-2">
                                            <span className={`px-2 py-1 rounded-md text-xs font-medium backdrop-blur-sm ${getModelBadgeColor(variation.modelId)}`}>
                                                {variation.modelName}
                                            </span>
                                            {isSelected && (
                                                <span className="w-6 h-6 bg-green-500 rounded-full flex items-center justify-center text-white text-sm shadow-lg">
                                                    ✓
                                                </span>
                                            )}
                                        </div>

                                        {/* Zoom Button */}
                                        {!failed && (
                                            <button
                                                onClick={(e) => {
                                                    e.stopPropagation()
                                                    setZoomedImage(variation.imageUrl)
                                                }}
                                                className="absolute top-3 right-3 z-10 w-8 h-8 bg-black/50 backdrop-blur-sm rounded-lg flex items-center justify-center text-white hover:bg-black/70 transition-colors"
                                            >
                                                🔍
                                            </button>
                                        )}

                                        {/* Image */}
                                        <div className="aspect-video bg-gray-800">
                                            <img
                                                src={variation.imageUrl}
                                                alt={`${variation.modelName} generation`}
                                                className="w-full h-full object-cover"
                                            />
                                        </div>

                                        {/* Footer */}
                                        <div className="p-3 bg-gray-900/90 border-t border-gray-700/50">
                                            {!failed ? (
                                                <button
                                                    onClick={(e) => {
                                                        e.stopPropagation()
                                                        onSelect(index)
                                                    }}
                                                    className={`w-full px-4 py-2 rounded-lg text-sm font-medium transition-colors ${isSelected
                                                        ? 'bg-green-600 text-white'
                                                        : 'bg-violet-600/20 text-violet-400 hover:bg-violet-600/30'
                                                        }`}
                                                >
                                                    {isSelected ? '✓ Selected' : 'Select This Image'}
                                                </button>
                                            ) : (
                                                <div className="text-gray-500 text-sm text-center py-2">
                                                    Generation failed
                                                </div>
                                            )}
                                        </div>
                                    </div>
                                )
                            })}
                        </div>
                    </div>

                    {/* Footer */}
                    <div className="p-6 border-t border-gray-700/50 flex items-center justify-between">
                        <p className="text-gray-400 text-sm">
                            Click to select, or use the zoom button to view full size
                        </p>
                        <div className="flex gap-3">
                            <button
                                onClick={onClose}
                                className="px-6 py-2.5 bg-gray-800 text-gray-300 rounded-lg hover:bg-gray-700 transition-colors"
                            >
                                Cancel
                            </button>
                            <button
                                onClick={onClose}
                                className="px-6 py-2.5 bg-gradient-to-r from-violet-600 to-purple-600 text-white rounded-lg font-medium hover:from-violet-700 hover:to-purple-700 shadow-lg shadow-violet-500/20"
                            >
                                Confirm Selection
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            {/* Zoom Modal */}
            {zoomedImage && (
                <div
                    className="fixed inset-0 bg-black/95 z-[60] flex items-center justify-center p-8 cursor-zoom-out"
                    onClick={() => setZoomedImage(null)}
                >
                    <img
                        src={zoomedImage}
                        alt="Zoomed image"
                        className="max-w-full max-h-full object-contain rounded-lg"
                    />
                    <button
                        onClick={() => setZoomedImage(null)}
                        className="absolute top-6 right-6 w-12 h-12 bg-gray-800 rounded-full flex items-center justify-center text-white hover:bg-gray-700 transition-colors"
                    >
                        ✕
                    </button>
                </div>
            )}
        </>
    )
}
