'use client'

import { useState } from 'react'
import { ContentVariation } from '@/app/campaigns/page'

interface VariationPickerProps {
    platform: string
    variations: ContentVariation[]
    selectedIndex: number
    onSelect: (index: number) => void
    onClose: () => void
}

export function VariationPicker({ platform, variations, selectedIndex, onSelect, onClose }: VariationPickerProps) {
    const [hoveredIndex, setHoveredIndex] = useState<number | null>(null)

    const getProviderColor = (provider: string) => {
        switch (provider.toLowerCase()) {
            case 'anthropic': return 'from-orange-500/20 to-amber-500/20 border-orange-500/50'
            case 'openai': return 'from-green-500/20 to-emerald-500/20 border-green-500/50'
            case 'google': return 'from-blue-500/20 to-cyan-500/20 border-blue-500/50'
            default: return 'from-violet-500/20 to-purple-500/20 border-violet-500/50'
        }
    }

    const getProviderBadgeColor = (provider: string) => {
        switch (provider.toLowerCase()) {
            case 'anthropic': return 'bg-orange-500/20 text-orange-400'
            case 'openai': return 'bg-green-500/20 text-green-400'
            case 'google': return 'bg-blue-500/20 text-blue-400'
            default: return 'bg-violet-500/20 text-violet-400'
        }
    }

    return (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-6">
            <div className="bg-gray-900 rounded-2xl border border-gray-700/50 w-full max-w-6xl max-h-[90vh] overflow-hidden flex flex-col">
                {/* Header */}
                <div className="p-6 border-b border-gray-700/50 flex items-center justify-between">
                    <div>
                        <h2 className="text-xl font-bold text-white flex items-center gap-2">
                            🤖 Pick Your Favorite
                        </h2>
                        <p className="text-gray-400 text-sm mt-1">
                            Compare {variations.length} variations generated by different AI models for <span className="text-violet-400 font-medium">{platform}</span>
                        </p>
                    </div>
                    <button
                        onClick={onClose}
                        className="w-10 h-10 rounded-lg bg-gray-800 text-gray-400 hover:text-white hover:bg-gray-700 transition-colors flex items-center justify-center"
                    >
                        ✕
                    </button>
                </div>

                {/* Variations Grid */}
                <div className="flex-1 overflow-auto p-6">
                    <div className={`grid gap-4 ${variations.length === 2 ? 'grid-cols-2' : 'grid-cols-3'}`}>
                        {variations.map((variation, index) => {
                            const isSelected = selectedIndex === index
                            const isHovered = hoveredIndex === index
                            const isFailed = variation.content.startsWith('[Generation failed')

                            return (
                                <div
                                    key={index}
                                    onClick={() => !isFailed && onSelect(index)}
                                    onMouseEnter={() => setHoveredIndex(index)}
                                    onMouseLeave={() => setHoveredIndex(null)}
                                    className={`
                                        relative rounded-xl border-2 transition-all cursor-pointer
                                        ${isFailed
                                            ? 'bg-gray-800/50 border-gray-700/50 opacity-50 cursor-not-allowed'
                                            : isSelected
                                                ? `bg-gradient-to-br ${getProviderColor(variation.provider)} shadow-lg`
                                                : isHovered
                                                    ? 'bg-gray-800/80 border-gray-600'
                                                    : 'bg-gray-800/50 border-gray-700/50'
                                        }
                                    `}
                                >
                                    {/* Model Header */}
                                    <div className="p-4 border-b border-gray-700/50">
                                        <div className="flex items-center justify-between">
                                            <div className="flex items-center gap-2">
                                                <span className={`px-2 py-1 rounded-md text-xs font-medium ${getProviderBadgeColor(variation.provider)}`}>
                                                    {variation.provider}
                                                </span>
                                                <span className="text-white font-medium">{variation.modelName}</span>
                                            </div>
                                            {isSelected && (
                                                <span className="w-6 h-6 bg-green-500 rounded-full flex items-center justify-center text-white text-sm">
                                                    ✓
                                                </span>
                                            )}
                                        </div>
                                    </div>

                                    {/* Content Preview */}
                                    <div className="p-4">
                                        {isFailed ? (
                                            <div className="text-gray-500 text-sm italic">
                                                Generation failed for this model
                                            </div>
                                        ) : (
                                            <pre className="text-gray-300 text-sm whitespace-pre-wrap font-sans leading-relaxed max-h-80 overflow-y-auto">
                                                {variation.content}
                                            </pre>
                                        )}
                                    </div>

                                    {/* Footer */}
                                    <div className="px-4 py-3 border-t border-gray-700/50 flex items-center justify-between">
                                        <span className="text-gray-500 text-xs">
                                            {variation.content.length} characters
                                        </span>
                                        {!isFailed && (
                                            <button
                                                onClick={(e) => {
                                                    e.stopPropagation()
                                                    onSelect(index)
                                                }}
                                                className={`px-4 py-1.5 rounded-lg text-sm font-medium transition-colors ${isSelected
                                                    ? 'bg-green-600 text-white'
                                                    : 'bg-violet-600/20 text-violet-400 hover:bg-violet-600/30'
                                                    }`}
                                            >
                                                {isSelected ? '✓ Selected' : 'Select This'}
                                            </button>
                                        )}
                                    </div>
                                </div>
                            )
                        })}
                    </div>
                </div>

                {/* Footer Actions */}
                <div className="p-6 border-t border-gray-700/50 flex items-center justify-between">
                    <p className="text-gray-400 text-sm">
                        Click on a variation to select it, or use the "Select This" button
                    </p>
                    <div className="flex gap-3">
                        <button
                            onClick={onClose}
                            className="px-6 py-2.5 bg-gray-800 text-gray-300 rounded-lg hover:bg-gray-700 transition-colors"
                        >
                            Cancel
                        </button>
                        <button
                            onClick={onClose}
                            className="px-6 py-2.5 bg-gradient-to-r from-violet-600 to-purple-600 text-white rounded-lg font-medium hover:from-violet-700 hover:to-purple-700 shadow-lg shadow-violet-500/20"
                        >
                            Confirm Selection
                        </button>
                    </div>
                </div>
            </div>
        </div>
    )
}
