import { NextRequest, NextResponse } from 'next/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { sendEmail } from '@/lib/postmark'

export const dynamic = 'force-dynamic'

// POST /api/ai-search-agent/send-report
export async function POST(request: NextRequest) {
  try {
    const supabase = createAdminClient()
    const { to, workspace_id } = await request.json()

    if (!to || !workspace_id) {
      return NextResponse.json({ error: 'to and workspace_id required' }, { status: 400 })
    }

    const { data: analysis } = await supabase
      .from('vera_website_analysis_results')
      .select('*')
      .eq('workspace_id', workspace_id)
      .eq('status', 'completed')
      .order('created_at', { ascending: false })
      .limit(1)
      .single()

    if (!analysis) {
      return NextResponse.json({ error: 'No completed analysis found' }, { status: 404 })
    }

    const htmlBody = `
      <div style="font-family: Inter, sans-serif; max-width: 600px; margin: 0 auto;">
        <h1 style="color: #3b82f6;">Vera.AI SEO/GEO Analysis Report</h1>
        <p><strong>Website:</strong> ${analysis.website_url}</p>
        <p><strong>Domain:</strong> ${analysis.domain}</p>
        <p><strong>Analyzed:</strong> ${new Date(analysis.analyzed_at).toLocaleDateString()}</p>
        <hr />
        <div style="display: flex; gap: 20px; margin: 20px 0;">
          <div style="text-align: center;">
            <div style="font-size: 36px; font-weight: bold; color: #3b82f6;">${analysis.seo_score || 'N/A'}</div>
            <div style="color: #6b7280;">SEO Score</div>
          </div>
          <div style="text-align: center;">
            <div style="font-size: 36px; font-weight: bold; color: #8b5cf6;">${analysis.geo_score || 'N/A'}</div>
            <div style="color: #6b7280;">GEO Score</div>
          </div>
          <div style="text-align: center;">
            <div style="font-size: 36px; font-weight: bold; color: #06b6d4;">${analysis.overall_score || 'N/A'}</div>
            <div style="color: #6b7280;">Overall</div>
          </div>
        </div>
        <hr />
        <h2>Executive Summary</h2>
        <p>${analysis.executive_summary || 'No summary available.'}</p>
        <hr />
        <p style="color: #6b7280; font-size: 12px;">Generated by Vera.AI | InnovareAI</p>
      </div>
    `

    await sendEmail({
      to,
      subject: `Vera.AI SEO/GEO Report: ${analysis.domain} — Score ${analysis.overall_score}/100`,
      htmlBody,
    })

    return NextResponse.json({ success: true, sent_to: to })
  } catch (error: unknown) {
    console.error('Send report error:', error)
    return NextResponse.json({ error: (error as Error).message }, { status: 500 })
  }
}
